# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: bazzite-custom-wifi
description: Bazzite Custom Image mit WLAN-Unterstützung für FRITZ!WLAN AC 860.

base-image: ghcr.io/ublue-os/bazzite-nvidia
image-version: stable

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: dnf
    repos:
      copr:
        - atim/starship
    install:
      packages:
        - micro
        - starship
        - kernel-firmware-mediatek
