
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: bazzite-custom-wifi
# description will be included in the image's metadata
description: Bazzite Custom Image mit integriertem RTL8812AU WLAN-Treiber.

# Bazzite als Basis wählen (passe 'bazzite' bei Bedarf an deine Edition an, z.B. bazzite-deck oder bazzite-gnome)
base-image: ghcr.io/ublue-os/bazzite-nvidia
image-version: latest

# module configuration, executed in order
modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: akmods
    install:
      - 8812au

  - type: dnf
    repos:
      copr:
        - atim/starship
    install:
      packages:
        - micro
        - starship
    remove:
      packages:
        - firefox
        - firefox-langpacks

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - org.mozilla.firefox
          - org.gnome.Loupe
      - scope: user

 
